In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Automobilecodedata.csv')

In [3]:
dataset

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,name,origin
0,18.0,8.0,307.0,130.0,3504.0,12.0,70.0,chevrolet chevelle malibu,usa
1,15.0,8.0,350.0,165.0,3693.0,11.5,70.0,buick skylark 320,usa
2,18.0,8.0,318.0,150.0,3436.0,11.0,70.0,plymouth satellite,usa
3,16.0,8.0,304.0,150.0,3433.0,12.0,70.0,amc rebel sst,usa
4,17.0,8.0,302.0,140.0,3449.0,10.5,70.0,ford torino,usa
...,...,...,...,...,...,...,...,...,...
393,27.0,4.0,140.0,86.0,2790.0,15.6,82.0,ford mustang gl,usa
394,44.0,4.0,97.0,52.0,2130.0,24.6,82.0,vw pickup,europe
395,32.0,4.0,135.0,84.0,2295.0,11.6,82.0,dodge rampage,usa
396,28.0,4.0,120.0,79.0,2625.0,18.6,82.0,ford ranger,usa
397,31.0,4.0,119.0,82.0,2720.0,19.4,82.0,chevy s-10,usa

In [4]:
dataset

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,name,origin
0,18.0,8.0,307.0,130.0,3504.0,12.0,70.0,chevrolet chevelle malibu,usa
1,15.0,8.0,350.0,165.0,3693.0,11.5,70.0,buick skylark 320,usa
2,18.0,8.0,318.0,150.0,3436.0,11.0,70.0,plymouth satellite,usa
3,16.0,8.0,304.0,150.0,3433.0,12.0,70.0,amc rebel sst,usa
4,17.0,8.0,302.0,140.0,3449.0,10.5,70.0,ford torino,usa
...,...,...,...,...,...,...,...,...,...
393,27.0,4.0,140.0,86.0,2790.0,15.6,82.0,ford mustang gl,usa
394,44.0,4.0,97.0,52.0,2130.0,24.6,82.0,vw pickup,europe
395,32.0,4.0,135.0,84.0,2295.0,11.6,82.0,dodge rampage,usa
396,28.0,4.0,120.0,79.0,2625.0,18.6,82.0,ford ranger,usa
397,31.0,4.0,119.0,82.0,2720.0,19.4,82.0,chevy s-10,usa

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,name_amc ambassador dpl,name_amc ambassador sst,name_amc concord,...,name_volvo 245,name_volvo 264gl,name_volvo diesel,name_vw dasher (diesel),name_vw pickup,name_vw rabbit,name_vw rabbit c (diesel),name_vw rabbit custom,origin_japan,origin_usa
0,18.0,8.0,307.0,130.0,3504.0,12.0,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,15.0,8.0,350.0,165.0,3693.0,11.5,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,18.0,8.0,318.0,150.0,3436.0,11.0,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,16.0,8.0,304.0,150.0,3433.0,12.0,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,17.0,8.0,302.0,140.0,3449.0,10.5,70.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4.0,140.0,86.0,2790.0,15.6,82.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
394,44.0,4.0,97.0,52.0,2130.0,24.6,82.0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
395,32.0,4.0,135.0,84.0,2295.0,11.6,82.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
396,28.0,4.0,120.0,79.0,2625.0,18.6,82.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
397,31.0,4.0,119.0,82.0,2720.0,19.4,82.0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
indep=dataset[['displacement', 'weight', 'model_year', 'cylinders']]
dep=dataset['mpg']

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [11]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [17]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 



grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=4,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

In [ ]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [ ]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

In [ ]:
print("The confusion Matrix:\n",cm)

In [ ]:
print("The report:\n",clf_report)

In [ ]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

In [ ]:
table=pd.DataFrame.from_dict(re)

In [ ]:
table

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))